### ISSUE TITLE
Undefined parameters

### ISSUE THREAD

**Issue by asagot** [UCLA-VAST/FlexCNN#10]
Neither the code nor the docs define the parameters located in 
https://github.com/UCLA-VAST/FlexCNN/blob/master/libsacc/inc/sacc_params.h

Do these need to be adjusted for different fpga platforms or different networks?

**Comment by atefehsz** [comment]
Those parameters will be defined by the instruction generator step. Some of the parameters are removed in the current version. But, they are kept there since the bitstream [here](https://github.com/UCLA-VAST/FlexCNN/blob/master/libsacc/config/binary_container_1.xclbin) needs them.

If you have followed the steps in the docs to generate your bitstream, you do not need the ones that inst_gen does not produce. libsacc library is now updated with this change.
