### ISSUE TITLE
HLS Simulation Fails to Build

### ISSUE THREAD

**Issue by asagot** [UCLA-VAST/FlexCNN#11]
When trying to recreate the design, when I when I run vivado_hls -f hls_script.tcl the project fails to finish csim. It complains about undefined macros. Looks like STRAGE2L_OFFSET and STAGE2R_OFFSET are not defined.

   Compiling ../../../../2DDataFeedCollect_U1.cpp in debug mode
   Compiling ../../../../2DDataCollect_U1.cpp in debug mode
   Compiling ../../../../2DDataFeed_U1.cpp in debug mode
   Compiling ../../../../cnn_sw.cpp in debug mode
csim.mk:100: recipe for target 'obj/cnn_sw.o' failed
../../../../cnn_sw.cpp: In function ‘void openpose_postprocess(data_t0*, data_t0 (*)[48][57])’:
../../../../cnn_sw.cpp:52:59: error: ‘STAGE2L_OFFSET’ was not declared in this scope
             LAYER_out[h][w][o + STAGE2R_OUT_NUM] = cin_hw[STAGE2L_OFFSET + o1 * STAGE2L_OUT_H_HW * STAGE2L_OUT_W_HW * STAGE2L_OUT_NUM_T + (h + int(STAGE2L_K / 2)) * STAGE2L_OUT_W_HW * STAGE2L_OUT_NUM_T + (w + int(STAGE2L_K / 2)) * STAGE2L_OUT_NUM_T + o2];
                                                           ^~~~~~~~~~~~~~
../../../../cnn_sw.cpp:61:41: error: ‘STAGE2R_OFFSET’ was not declared in this scope
             LAYER_out[h][w][o] = cin_hw[STAGE2R_OFFSET + o1 * STAGE2R_OUT_H_HW * STAGE2R_OUT_W_HW * STAGE2R_OUT_NUM_T + (h + int(STAGE2R_K / 2)) * STAGE2R_OUT_W_HW * STAGE2R_OUT_NUM_T + (w + int(STAGE2R_K / 2)) * STAGE2R_OUT_NUM_T + o2];
                                         ^~~~~~~~~~~~~~
make: *** [obj/cnn_sw.o] Error 1
ERROR: [SIM 211-100] CSim file generat

**Comment by zzzDavid** [comment]
I ran into the same problems, too. I think those two constants could be 
```c++
#define STAGE2L_OFFSET 12160160
#define STAGE2R_OFFSET 12280160
```

Saw it in `libsacc/inc/sacc_params.h`.

**Comment by asagot** [comment]
Were you able to run the HLS sim ?

**Comment by atefehsz** [comment]
The value of these variables depends on the tensor you want to check as they should specify the starting address in DRAM where that tensor is stored.
OpenPose network outputs two tensors so we save the offset for those tensors and check the value of those tensors in openpose_postprocess function. Since this value should be specified according to the target CNN, they were removed from the inst_gen code. Check out [here](https://github.com/UCLA-VAST/FlexCNN/blob/master/auto_compile/inst_gen/inst_parse.py#L909) to see how you can specify these values for OpenPose network. But remember that you should modify them for any new network.
